version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres_home
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homedb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
